// docs/tests/run-conversion.test.ts
//
// Unit tests for the conversion dispatch boundary in docs/tools/conversion.ts.
// This is the UI ↔ library seam: the function the click handler calls when
// the user hits Generate. We test the dispatch shape, the filename
// construction, the array contract, and the error path — not the underlying
// ODF generation correctness (that's covered by the library's own tests).
//
// Coverage as of the binary-preview fan-out:
//   - The four text→ODT pathways (html, markdown, lexical, tiptap): bytes-kind
//     result shape, previewText, filename construction, array contract.
//   - docx→odt: bytes-kind ODT result. The DOCX input is a real, minimal Word
//     document committed at docs/tests/sample.docx (see fixture note below).
//   - odt→html: the first text-kind result the dispatch produces. The ODT
//     input is manufactured in-test via htmlToOdt — for ODT we can generate
//     a valid input by running the library forward, so no fixture is needed.
//   - previewBinary: the input-pane preview helper. odt (generated) and docx
//     (fixture) return non-empty HTML; xlsx/ods assert the not-yet-implemented
//     guard (their preview needs the sheet-tab renderer, a later commit).
//   - Error path: tracks the frontier of unimplemented pairs.
//
// Fixture note: this is the only test in the suite that loads a file from
// disk. Every other input is an inline string or generated by running the
// library forward. DOCX is the exception because the library has no DOCX
// writer — there is no way to manufacture valid .docx bytes in-test — so a
// real, minimal Word document (a single "Hello world." line, OOXML / Word
// 2010 .docx format) is committed at docs/tests/sample.docx and read here.
// The path is resolved from import.meta.url (ESM: __dirname is unavailable)
// so it is independent of the working directory the runner is invoked from.
//
// Located in docs/tests/ (sibling to docs/tools/) so the page's tests live
// adjacent to the page source, distinct from the library's tests/ directory
// at the repository root.

import { readFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { describe, expect, test } from "@jest/globals";
import { htmlToOdt } from "odf-kit/odt";

import { previewBinary, runConversion, type ConversionInput } from "../tools/conversion.js";

// ─────────────────────────────────────────────────────────────────────────────
// Test fixtures
// ─────────────────────────────────────────────────────────────────────────────
//
// Small but real HTML5 input — enough that htmlToOdt produces a valid ODT
// document. Doc structure is intentionally bare so the test isn't sensitive
// to library-side rendering choices (paragraph spacing, span wrappers, etc.).
// What we check is that something non-empty came out and is shaped correctly.
// Doubles as the source for the odt→html and previewBinary(odt) tests: running
// htmlToOdt on it yields a valid ODT to feed back through the reader path.

const MINIMAL_HTML = "<!DOCTYPE html><html><body><p>Hello world</p></body></html>";

// Small but real CommonMark input — enough that markdownToOdt (Markdown →
// HTML via marked, then htmlToOdt) produces a valid ODT document. As with
// the HTML fixture, the structure is bare so the test isn't sensitive to
// library-side rendering choices; we check shape, not exact bytes.
const MINIMAL_MARKDOWN = "# Hello\n\nWorld";

// Minimal valid Lexical SerializedEditorState as a JSON *string* — this is
// how it arrives at runConversion (ConversionInput.text carries the raw file
// / sample / typed text; the lexical case JSON.parses it before calling
// lexicalToOdt, which takes a parsed object). A root with one paragraph and
// one text node is the smallest structure the walker renders to a valid ODT.
const MINIMAL_LEXICAL = JSON.stringify({
  root: {
    type: "root",
    version: 1,
    direction: "ltr",
    format: "",
    indent: 0,
    children: [
      {
        type: "paragraph",
        version: 1,
        direction: "ltr",
        format: "",
        indent: 0,
        children: [
          {
            type: "text",
            version: 1,
            text: "Hello world",
            format: 0,
            style: "",
            mode: "normal",
            detail: 0,
          },
        ],
      },
    ],
  },
});

// Minimal valid TipTap JSONContent document as a JSON *string* — same arrival
// path as lexical (ConversionInput.text carries raw JSON; the tiptap case
// JSON.parses it before calling tiptapToOdt, which takes a parsed object with
// type "doc"). A doc with one paragraph and one text node is the smallest
// structure tiptapToOdt renders to a valid ODT.
const MINIMAL_TIPTAP = JSON.stringify({
  type: "doc",
  content: [
    {
      type: "paragraph",
      content: [{ type: "text", text: "Hello world" }],
    },
  ],
});

// Real DOCX bytes from the committed fixture (see "Fixture note" in the header).
// Read once at module load; a missing file throws here with a clear path.
// readFileSync returns a Buffer; wrap in a fresh Uint8Array so the value
// matches ConversionInput's `bytes: Uint8Array` shape exactly (and owns its
// own backing buffer rather than a slice of Node's shared pool).
const FIXTURE_DIR = dirname(fileURLToPath(import.meta.url));
const SAMPLE_DOCX_BYTES = new Uint8Array(readFileSync(join(FIXTURE_DIR, "sample.docx")));

describe("runConversion(html → odt)", () => {
  test("happy path: returns bytes-kind result with all expected fields", async () => {
    const input: ConversionInput = {
      inputFormat: "html",
      text: MINIMAL_HTML,
      inputFilename: "fixture.html",
    };
    const results = await runConversion([input], "odt");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("bytes");
    if (result.kind !== "bytes") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("odt");
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(typeof result.previewText).toBe("string");
    expect(result.previewText.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("fixture.odt");
  });

  test("filename construction: input with extension produces stem + .odt", async () => {
    const input: ConversionInput = {
      inputFormat: "html",
      text: MINIMAL_HTML,
      inputFilename: "report.html",
    };
    const results = await runConversion([input], "odt");
    expect(results[0]!.outputFilename).toBe("report.odt");
  });

  test("filename construction: input without extension uses whole string as stem", async () => {
    // Reached when the user typed input via keyboard — onKeyboardClick
    // sets inputFilename to "Document" with no extension. parseFilename
    // reports no-extension; buildOutputFilename falls back to whole-string
    // and appends the output extension.
    const input: ConversionInput = {
      inputFormat: "html",
      text: MINIMAL_HTML,
      inputFilename: "Document",
    };
    const results = await runConversion([input], "odt");
    expect(results[0]!.outputFilename).toBe("Document.odt");
  });

  test("array contract: two inputs produce two results in submitted order", async () => {
    const inputs: ConversionInput[] = [
      {
        inputFormat: "html",
        text: "<p>first</p>",
        inputFilename: "first.html",
      },
      {
        inputFormat: "html",
        text: "<p>second</p>",
        inputFilename: "second.html",
      },
    ];
    const results = await runConversion(inputs, "odt");
    expect(results).toHaveLength(2);
    expect(results[0]!.outputFilename).toBe("first.odt");
    expect(results[1]!.outputFilename).toBe("second.odt");
  });
});

describe("runConversion(markdown → odt)", () => {
  test("happy path: returns bytes-kind result with all expected fields", async () => {
    const input: ConversionInput = {
      inputFormat: "markdown",
      text: MINIMAL_MARKDOWN,
      inputFilename: "fixture.md",
    };
    const results = await runConversion([input], "odt");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("bytes");
    if (result.kind !== "bytes") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("odt");
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(typeof result.previewText).toBe("string");
    expect(result.previewText.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("fixture.odt");
  });
});

describe("runConversion(lexical → odt)", () => {
  test("happy path: returns bytes-kind result with all expected fields", async () => {
    const input: ConversionInput = {
      inputFormat: "lexical",
      text: MINIMAL_LEXICAL,
      inputFilename: "sample_lexical.json",
    };
    const results = await runConversion([input], "odt");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("bytes");
    if (result.kind !== "bytes") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("odt");
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(typeof result.previewText).toBe("string");
    expect(result.previewText.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("sample_lexical.odt");
  });
});

describe("runConversion(tiptap → odt)", () => {
  test("happy path: returns bytes-kind result with all expected fields", async () => {
    const input: ConversionInput = {
      inputFormat: "tiptap",
      text: MINIMAL_TIPTAP,
      inputFilename: "sample_tiptap.json",
    };
    const results = await runConversion([input], "odt");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("bytes");
    if (result.kind !== "bytes") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("odt");
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(typeof result.previewText).toBe("string");
    expect(result.previewText.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("sample_tiptap.odt");
  });
});

describe("runConversion(docx → odt)", () => {
  test("happy path: returns bytes-kind result with all expected fields", async () => {
    // Real Word file from the committed fixture. If docxToOdt cannot parse a
    // stock OOXML document, this fails — and that is real signal about the
    // docx reader, not a test to paper over. The dispatch shape is the same
    // as the text→ODT pathways (bytes-kind ODT + previewText + .odt name);
    // the docx-specific value here is that a genuine Word file round-trips.
    const input: ConversionInput = {
      inputFormat: "docx",
      bytes: SAMPLE_DOCX_BYTES,
      inputFilename: "sample.docx",
    };
    const results = await runConversion([input], "odt");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("bytes");
    if (result.kind !== "bytes") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("odt");
    expect(result.bytes).toBeInstanceOf(Uint8Array);
    expect(result.bytes.length).toBeGreaterThan(0);
    expect(typeof result.previewText).toBe("string");
    expect(result.previewText.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("sample.odt");
  });
});

describe("runConversion(odt → html)", () => {
  test("happy path: returns text-kind result with all expected fields", async () => {
    // Manufacture a valid ODT input by running htmlToOdt on minimal HTML —
    // self-contained, no on-disk fixture, matching this suite's
    // generate-don't-load convention for everything except DOCX. odt→html is
    // the first text-kind result the dispatch produces (kind:"text" /
    // outputFormat:"html"), so it exercises the previously-untested text
    // branch of the result shape.
    const odtBytes = await htmlToOdt(MINIMAL_HTML);
    const input: ConversionInput = {
      inputFormat: "odt",
      bytes: odtBytes,
      inputFilename: "fixture.odt",
    };
    const results = await runConversion([input], "html");
    expect(results).toHaveLength(1);

    const result = results[0]!;
    expect(result.kind).toBe("text");
    if (result.kind !== "text") return; // Narrowing for TypeScript
    expect(result.outputFormat).toBe("html");
    expect(typeof result.text).toBe("string");
    expect(result.text.length).toBeGreaterThan(0);
    expect(result.outputFilename).toBe("fixture.html");
  });

  test("filename construction: .odt input maps to .html output extension", async () => {
    // First pathway whose output extension differs from the input's — guards
    // the input-extension → output-extension mapping in buildOutputFilename
    // (every prior pathway happened to output .odt).
    const odtBytes = await htmlToOdt(MINIMAL_HTML);
    const input: ConversionInput = {
      inputFormat: "odt",
      bytes: odtBytes,
      inputFilename: "report.odt",
    };
    const results = await runConversion([input], "html");
    expect(results[0]!.outputFilename).toBe("report.html");
  });
});

describe("previewBinary", () => {
  test("odt: returns a non-empty HTML preview string", async () => {
    // previewBinary(odt) is odtToHtml(bytes) directly. Generated-ODT approach,
    // same as the odt→html tests. We assert it produces a usable preview
    // string, not its exact HTML.
    const odtBytes = await htmlToOdt(MINIMAL_HTML);
    const html = await previewBinary(odtBytes, "odt");
    expect(typeof html).toBe("string");
    expect(html.length).toBeGreaterThan(0);
  });

  test("docx: returns a non-empty HTML preview string", async () => {
    // previewBinary(docx) is docxToOdt(bytes) → odtToHtml(...). Uses the
    // committed sample.docx fixture. Same docx-parse dependency as the
    // docx→odt test above.
    const html = await previewBinary(SAMPLE_DOCX_BYTES, "docx");
    expect(typeof html).toBe("string");
    expect(html.length).toBeGreaterThan(0);
  });

  test("xlsx and ods throw not-yet-implemented (sheet-tab renderer pending)", async () => {
    // Their preview path needs the sheet-tab renderer (a later commit), so
    // loadBinaryFile must not route them to previewBinary yet; the throw keeps
    // that boundary honest. Empty bytes suffice — the guard fires before any
    // parsing.
    await expect(previewBinary(new Uint8Array(), "xlsx")).rejects.toThrow(
      /not yet implemented.*xlsx/,
    );
    await expect(previewBinary(new Uint8Array(), "ods")).rejects.toThrow(
      /not yet implemented.*ods/,
    );
  });
});

describe("runConversion error paths", () => {
  test("not-yet-implemented pair throws with descriptive message", async () => {
    // The specimen tracks the frontier of unimplemented pathways. docx→odt
    // and odt→html are now wired, so the closest remaining binary-input
    // "not yet implemented" pair is xlsx→ods — note the bytes shape (xlsx
    // carries a Uint8Array). The dispatch throws before reading the bytes,
    // so an empty array is sufficient. Re-point to the next still-
    // unimplemented pathway (odt→markdown, odt→typst, ods→html) as each
    // remaining fan-out commit lands.
    const input: ConversionInput = {
      inputFormat: "xlsx",
      bytes: new Uint8Array(),
      inputFilename: "test.xlsx",
    };
    await expect(runConversion([input], "ods")).rejects.toThrow(/not yet implemented.*xlsx.*ods/);
  });
});
