/**
 * generate-showcase.ts
 *
 * Generates a showcase .odt file demonstrating all odf-kit features.
 * Place this file in your odf-kit project root and run:
 *
 *   npx tsx generate-showcase.ts
 *
 * (Install tsx first if needed: npm install -D tsx)
 *
 * Or compile and run:
 *   npx tsc generate-showcase.ts --module nodenext --moduleResolution nodenext --target es2022 --outDir tmp
 *   node tmp/generate-showcase.js
 *
 * Output: showcase.odt (open in LibreOffice)
 */

import { writeFile } from "node:fs/promises";
import { OdtDocument } from "./src/odt/document.js";

async function main() {
  const doc = new OdtDocument();

  // --- Metadata ---
  doc.setMetadata({
    title: "odf-kit Feature Showcase",
    creator: "odf-kit v0.1.0",
  });

  // --- Page layout ---
  doc.setPageLayout({
    orientation: "portrait",
    marginTop: "2.5cm",
    marginBottom: "2.5cm",
    marginLeft: "2.5cm",
    marginRight: "2.5cm",
  });

  // --- Header and footer ---
  doc.setHeader((h) => {
    h.addText("odf-kit Feature Showcase", { bold: true, fontSize: 10 });
  });

  doc.setFooter((f) => {
    f.addText("Page ", { fontSize: 9, color: "gray" });
    f.addPageNumber({ fontSize: 9, color: "gray" });
    f.addText(" — Generated by odf-kit", { fontSize: 9, color: "gray", italic: true });
  });

  // ==========================================
  // TITLE
  // ==========================================
  doc.addHeading("odf-kit Feature Showcase", 1);
  doc.addParagraph(
    "This document was generated programmatically by odf-kit, a TypeScript library for creating ODF text documents. Every element you see — headings, formatted text, tables, lists, and page layout — was produced by the library's API.",
  );

  // ==========================================
  // TEXT FORMATTING
  // ==========================================
  doc.addHeading("1. Text Formatting", 2);

  doc.addParagraph((p) => {
    p.addText("odf-kit supports ");
    p.addText("bold", { bold: true });
    p.addText(", ");
    p.addText("italic", { italic: true });
    p.addText(", ");
    p.addText("bold italic", { bold: true, italic: true });
    p.addText(", ");
    p.addText("underline", { underline: true });
    p.addText(", ");
    p.addText("strikethrough", { strikethrough: true });
    p.addText(", ");
    p.addText("superscript", { superscript: true });
    p.addText(", and ");
    p.addText("subscript", { subscript: true });
    p.addText(" text.");
  });

  doc.addParagraph((p) => {
    p.addText("Font sizes: ");
    p.addText("10pt ", { fontSize: 10 });
    p.addText("12pt ", { fontSize: 12 });
    p.addText("16pt ", { fontSize: 16 });
    p.addText("20pt", { fontSize: 20 });
  });

  doc.addParagraph((p) => {
    p.addText("Colors: ");
    p.addText("red ", { color: "red", bold: true });
    p.addText("blue ", { color: "blue", bold: true });
    p.addText("green ", { color: "green", bold: true });
    p.addText("orange ", { color: "orange", bold: true });
    p.addText("highlighted", { highlightColor: "yellow", bold: true });
  });

  doc.addParagraph((p) => {
    p.addText("Font families: ");
    p.addText("Arial ", { fontFamily: "Arial" });
    p.addText("Times New Roman ", { fontFamily: "Times New Roman" });
    p.addText("Courier New", { fontFamily: "Courier New" });
  });

  doc.addParagraph((p) => {
    p.addText("Chemical formula: H");
    p.addText("2", { subscript: true });
    p.addText("O + CO");
    p.addText("2", { subscript: true });
    p.addText(" → H");
    p.addText("2", { subscript: true });
    p.addText("CO");
    p.addText("3", { subscript: true });
  });

  doc.addParagraph((p) => {
    p.addText("Mathematical: x");
    p.addText("2", { superscript: true });
    p.addText(" + y");
    p.addText("2", { superscript: true });
    p.addText(" = z");
    p.addText("2", { superscript: true });
  });

  // ==========================================
  // TABLES
  // ==========================================
  doc.addHeading("2. Tables", 2);

  doc.addParagraph("Simple table from array of arrays:");

  doc.addTable(
    [
      ["Language", "Typing", "Runtime"],
      ["TypeScript", "Static", "Node.js / Deno / Bun"],
      ["Python", "Dynamic", "CPython / PyPy"],
      ["Rust", "Static", "Native (compiled)"],
      ["Go", "Static", "Native (compiled)"],
    ],
    { border: "0.5pt solid #000000", columnWidths: ["4cm", "3cm", "6cm"] },
  );

  doc.addParagraph("Table with formatting via builder callback:");

  doc.addTable(
    (t) => {
      // Header row
      t.addRow((r) => {
        r.addCell("Feature", {
          bold: true,
          backgroundColor: "#336699",
          color: "white",
        });
        r.addCell("Status", {
          bold: true,
          backgroundColor: "#336699",
          color: "white",
        });
        r.addCell("Phase", {
          bold: true,
          backgroundColor: "#336699",
          color: "white",
        });
      });
      // Data rows
      t.addRow((r) => {
        r.addCell("Paragraphs & headings", { backgroundColor: "#f0f0f0" });
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("1");
      });
      t.addRow((r) => {
        r.addCell("Text formatting");
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("1");
      });
      t.addRow((r) => {
        r.addCell("Tables", { backgroundColor: "#f0f0f0" });
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("2");
      });
      t.addRow((r) => {
        r.addCell("Page layout");
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("3");
      });
      t.addRow((r) => {
        r.addCell("Lists", { backgroundColor: "#f0f0f0" });
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("4");
      });
      t.addRow((r) => {
        r.addCell("Images & links");
        r.addCell("Complete", { color: "green", bold: true });
        r.addCell("5");
      });
      t.addRow((r) => {
        r.addCell("ODS (spreadsheets)", { backgroundColor: "#f0f0f0" });
        r.addCell("Planned", { color: "orange", italic: true });
        r.addCell("Future");
      });
    },
    { border: "0.5pt solid #999999", columnWidths: ["6cm", "4cm", "3cm"] },
  );

  // ==========================================
  // LISTS
  // ==========================================
  doc.addHeading("3. Lists", 2);

  doc.addParagraph("Bullet list:");
  doc.addList(["First item", "Second item", "Third item"]);

  doc.addParagraph("Numbered list:");
  doc.addList(["Step one: install odf-kit", "Step two: create a document", "Step three: save and open"], {
    type: "numbered",
  });

  doc.addParagraph("Nested list with formatting:");
  doc.addList((l) => {
    l.addItem("Document types supported:");
    l.addNested((sub) => {
      sub.addItem((p) => {
        p.addText("ODT", { bold: true });
        p.addText(" — text documents (Writer)");
      });
      sub.addItem((p) => {
        p.addText("ODS", { bold: true });
        p.addText(" — spreadsheets (Calc) — planned");
      });
      sub.addItem((p) => {
        p.addText("ODP", { bold: true });
        p.addText(" — presentations (Impress) — planned");
      });
    });
    l.addItem("Design principles:");
    l.addNested((sub) => {
      sub.addItem("Simple things stay simple");
      sub.addItem("Convention over novelty");
      sub.addItem("Be flexible and forgiving");
      sub.addNested((subsub) => {
        subsub.addItem("Accept multiple input formats");
        subsub.addItem("TypeScript figures out the rest");
      });
    });
  });

  // ==========================================
  // TAB STOPS
  // ==========================================
  doc.addHeading("4. Tab Stops", 2);

  doc.addParagraph(
    (p) => {
      p.addText("Item", { bold: true });
      p.addTab();
      p.addText("Qty", { bold: true });
      p.addTab();
      p.addText("Price", { bold: true });
    },
    { tabStops: [{ position: "6cm" }, { position: "12cm", type: "right" }] },
  );
  doc.addParagraph(
    (p) => {
      p.addText("Widget A");
      p.addTab();
      p.addText("100");
      p.addTab();
      p.addText("$5.00");
    },
    { tabStops: [{ position: "6cm" }, { position: "12cm", type: "right" }] },
  );
  doc.addParagraph(
    (p) => {
      p.addText("Widget B");
      p.addTab();
      p.addText("250");
      p.addTab();
      p.addText("$3.50");
    },
    { tabStops: [{ position: "6cm" }, { position: "12cm", type: "right" }] },
  );
  doc.addParagraph(
    (p) => {
      p.addText("Total", { bold: true });
      p.addTab();
      p.addText("350", { bold: true });
      p.addTab();
      p.addText("$1,375.00", { bold: true });
    },
    { tabStops: [{ position: "6cm" }, { position: "12cm", type: "right" }] },
  );

  // ==========================================
  // HYPERLINKS AND BOOKMARKS
  // ==========================================
  doc.addHeading("5. Hyperlinks and Bookmarks", 2);

  doc.addParagraph((p) => {
    p.addBookmark("links-section");
    p.addText("This paragraph has a bookmark named 'links-section'. ");
    p.addText("You can link to ");
    p.addLink("the odf-kit GitHub repo", "https://github.com/GitHubNewbie0/odf-kit");
    p.addText(" or to ");
    p.addLink("the npm package", "https://www.npmjs.com/package/odf-kit");
    p.addText(".");
  });

  doc.addParagraph((p) => {
    p.addText("Formatted links also work: ");
    p.addLink("Click here for odf-kit", "https://github.com/GitHubNewbie0/odf-kit", {
      bold: true,
      color: "blue",
    });
  });

  // ==========================================
  // PAGE BREAK
  // ==========================================
  doc.addPageBreak();

  // ==========================================
  // PAGE 2
  // ==========================================
  doc.addHeading("6. Page Breaks and Multi-Page Documents", 2);

  doc.addParagraph(
    "This content appears on page 2, after a page break. The header and footer carry over automatically. Page numbers update correctly.",
  );

  doc.addParagraph((p) => {
    p.addText("Internal links work too: ");
    p.addLink("Jump back to the links section", "#links-section");
    p.addText(" on page 1.");
  });

  // ==========================================
  // ABOUT
  // ==========================================
  doc.addHeading("About odf-kit", 2);

  doc.addParagraph((p) => {
    p.addText("odf-kit", { bold: true });
    p.addText(
      " is an open-source TypeScript library (Apache 2.0) for generating ODF text documents. It produces valid .odt files that open in LibreOffice, Google Docs, and Microsoft Office.",
    );
  });

  doc.addParagraph((p) => {
    p.addText("Key facts: ", { bold: true });
    p.addText(
      "Single runtime dependency (jszip). 102 tests. Full TypeScript types with autocomplete. Node 22+, ESM-only. Targets ODF 1.2+ (ISO/IEC 26300).",
    );
  });

  doc.addParagraph((p) => {
    p.addText("GitHub: ", { bold: true });
    p.addLink(
      "github.com/GitHubNewbie0/odf-kit",
      "https://github.com/GitHubNewbie0/odf-kit",
    );
  });

  doc.addParagraph((p) => {
    p.addText("npm: ", { bold: true });
    p.addLink(
      "npmjs.com/package/odf-kit",
      "https://www.npmjs.com/package/odf-kit",
    );
  });

  // --- Save ---
  const bytes = await doc.save();
  await writeFile("showcase.odt", bytes);
  console.log("✓ showcase.odt generated (%d bytes)", bytes.length);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
