// scripts/sync-version.js
//
// Single source of truth for odf-kit's version is package.json.
// This script propagates that version to two other places that
// historically had to be updated manually and were therefore prone
// to drift:
//
//   1. src/version.ts — exported as VERSION from the library so
//      runtime consumers (notably the tool pages on docs.) can
//      report the actual version of the code that loaded.
//
//   2. docs/index.html — the hero badge on the landing page.
//
// Wired into the npm build and prepare lifecycle hooks. Every build
// and every fresh `npm install` regenerates src/version.ts, so a
// clone of the repo can run `tsc` immediately without first having
// to remember to bump anything.

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(__dirname, "..");

// 1. Read the canonical version from package.json
const pkgPath = join(repoRoot, "package.json");
const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
const version = pkg.version;

if (!/^\d+\.\d+\.\d+/.test(version)) {
  console.error(`sync-version: package.json version "${version}" is not semver-shaped`);
  process.exit(1);
}

// 2. Write src/version.ts — generated TypeScript file. Git-ignored.
const versionTsPath = join(repoRoot, "src", "version.ts");
const versionTsContent =
  "// GENERATED FILE — do not edit by hand.\n" +
  "// Source of truth: package.json. Regenerated by scripts/sync-version.js.\n" +
  "//\n" +
  "// Re-exported from src/index.ts as the public `VERSION` constant.\n" +
  "// Tool pages on docs.githubnewbie0.github.io import this so error\n" +
  "// reports always reflect the version of the code that loaded.\n" +
  "\n" +
  `export const VERSION = "${version}";\n`;
writeFileSync(versionTsPath, versionTsContent, "utf8");

// 3. Update docs/index.html hero badge.
//    Match: <div class="hero-badge">v0.0.0 · ...
//    Substitute the v0.0.0 portion with the package version.
const indexHtmlPath = join(repoRoot, "docs", "index.html");
let indexHtml = readFileSync(indexHtmlPath, "utf8");
const heroBadgeRe = /(<div class="hero-badge">)v\d+\.\d+\.\d+(\s*·)/;
if (!heroBadgeRe.test(indexHtml)) {
  console.error(`sync-version: hero-badge pattern not found in docs/index.html`);
  process.exit(1);
}
indexHtml = indexHtml.replace(heroBadgeRe, `$1v${version}$2`);
writeFileSync(indexHtmlPath, indexHtml, "utf8");

console.log(`sync-version: VERSION=${version} written to src/version.ts and docs/index.html`);
